import json
import os

JSON_FILE = r"C:\Users\Phan Thuan\.gemini\antigravity\skills-guide\skills_data.json"

# Vietnamese translation mappings
translations = {
    "Folder Organization System": "Hệ thống hóa và tổ chức lại cấu trúc folder/file một cách khoa học, có thể áp dụng cho cá nhân hoặc doanh nghiệp.",
    "accessibility-review": "Audit thiết kế và code theo chuẩn WCAG 2.1 AA. Kích hoạt khi hỏi về khả năng tiếp cận, kiểm tra WCAG, hoặc tương thích trình đọc màn hình.",
    "account-research": "Nghiên cứu công ty hoặc cá nhân để thu thập thông tin bán hàng giá trị. Hoạt động độc lập với tìm kiếm web hoặc mạnh mẽ hơn khi kết nối CRM.",
    "agency-accessibility-auditor": "Chuyên gia kiểm định khả năng tiếp cận, audit giao diện theo tiêu chuẩn WCAG và đảm bảo thiết kế bao trùm cho mọi người dùng.",
    "agency-account-strategist": "Chiến lược gia tài khoản sau bán hàng, chuyên về mở rộng tài khoản, lập bản đồ bên liên quan và duy trì doanh thu hợp đồng.",
    "agency-accounts-payable-agent": "Chuyên gia xử lý thanh toán tự động cho nhà cung cấp, hóa đơn nhà thầu qua crypto, tiền định danh hoặc stablecoin.",
    "agency-ad-creative-strategist": "Chuyên gia sáng tạo nội dung quảng cáo trả phí, tối ưu hóa RSA và thử nghiệm nội dung trên Google, Meta, Microsoft.",
    "agency-agentic-identity-trust-architect": "Kiến trúc sư thiết kế hệ thống định danh và niềm tin cho các AI agent tự hành trong môi trường đa tác nhân.",
    "agency-agents-orchestrator": "Quản lý quy trình tự động, điều phối toàn bộ luồng phát triển. Đây là lãnh đạo của quy trình này.",
    "agency-ai-data-remediation-engineer": "Chuyên gia về đường ống dữ liệu tự phục hồi, sử dụng SLM để phát hiện và sửa lỗi dữ liệu quy mô lớn mà không làm dừng quy trình.",
    "agency-ai-engineer": "Kỹ sư AI/ML chuyên nghiệp, phát triển và tích hợp các mô hình học máy vào hệ thống sản xuất thực tế.",
    "agency-analytics-reporter": "Chuyên gia phân tích dữ liệu chuyên sâu, biến dữ liệu thô thành thông tin kinh doanh hữu ích qua dashboard và báo cáo.",
    "agency-api-tester": "Chuyên gia kiểm thử API toàn diện, xác thực hiệu suất và đảm bảo chất lượng trên mọi hệ thống tích hợp.",
    "agency-app-store-optimizer": "Chuyên gia marketing cửa hàng ứng dụng, tập trung vào ASO, tối ưu tỷ lệ chuyển đổi và khả năng tìm kiếm ứng dụng.",
    "agency-automation-governance-architect": "Kiến trúc sư nội bộ cho tự động hóa kinh doanh, audit giá trị, rủi ro và khả năng bảo trì trước khi triển khai.",
    "agency-autonomous-optimization-architect": "Người quản trị hệ thống thông minh, liên tục chạy shadow-test các API để kiểm tra hiệu suất và kiểm soát chi phí.",
    "agency-backend-architect": "Kiến trúc sư backend cao cấp, chuyên thiết kế hệ thống mở rộng, DB architecture và hạ tầng đám mây hiệu năng cao.",
    "agency-behavioral-nudge-engine": "Chuyên gia tâm lý học hành vi, điều chỉnh phong cách tương tác phần mềm để tối đa hóa động lực người dùng.",
    "agency-blockchain-security-auditor": "Chuyên gia audit bảo mật smart contract, phát hiện lỗ hổng và phân tích khai thác cho các giao thức DeFi.",
    "agency-book-co-author": "Cộng tác viên chiến lược viết sách cho lãnh đạo, biến các ghi chú rời rạc thành các chương sách có cấu trúc.",
    "agency-brand-guardian": "Chuyên gia chiến lược và bảo vệ thương hiệu, duy trì tính nhất quán và định vị thương hiệu trên thị trường.",
    "agency-carousel-growth-engine": "Chuyên gia tạo nội dung carousel tự động cho TikTok/Instagram, phân tích URL và đăng bài kèm nhạc xu hướng.",
    "agency-code-reviewer": "Chuyên gia review code tập trung vào tính chính xác, khả năng bảo trì, bảo mật và hiệu năng.",
    "agency-compliance-auditor": "Chuyên gia audit tuân thủ kỹ thuật (SOC 2, ISO 27001, HIPAA) từ đánh giá đến khi đạt chứng nhận.",
    "agency-content-creator": "Chuyên gia chiến lược và sáng tạo nội dung đa nền tảng, quản lý lịch biên tập và kể chuyện thương hiệu.",
    "agency-corporate-training-designer": "Chuyên gia thiết kế hệ thống đào tạo doanh nghiệp và chương trình giảng dạy, đánh giá hiệu quả đào tạo.",
    "agency-cultural-intelligence-strategist": "Chuyên gia trí tuệ văn hóa, đảm bảo phần mềm cộng hưởng chân thực với các bản sắc văn hóa toàn cầu.",
    "agency-data-consolidation-agent": "AI agent tổng hợp dữ liệu bán hàng vào dashboard báo cáo trực tiếp theo khu vực và phễu khách hàng.",
    "agency-data-engineer": "Kỹ sư dữ liệu chuyên nghiệp, xây dựng đường ống dữ liệu tin cậy (ETL/ELT) và kiến trúc lakehouse mở rộng.",
    "agency-database-optimizer": "Chuyên gia tối ưu hóa DB, thiết kế schema, tối ưu truy vấn và tinh chỉnh hiệu năng cho PostgreSQL/MySQL.",
    "agency-deal-strategist": "Chiến lược gia thương vụ cao cấp, chuyên về quy trình MEDDPICC và lập kế hoạch thắng thầu B2B phức tạp.",
    "agency-developer-advocate": "Chuyên gia cộng đồng lập trình viên, tối ưu trải nghiệm DX và thúc đẩy việc sử dụng nền tảng.",
    "agency-devops-automator": "Kỹ sư DevOps chuyên nghiệp, tự động hóa hạ tầng và vận hành hệ thống đám mây (CI/CD).",
    "agency-discovery-coach": "Huấn luyện đội ngũ bán hàng về phương pháp khai thác thông tin, tìm kiếm động lực mua hàng thực sự.",
    "agency-document-generator": "Chuyên gia tạo tài liệu chuyên nghiệp (PDF, PPTX, DOCX) bằng mã nguồn với biểu đồ sắc nét.",
    "agency-embedded-firmware-engineer": "Kỹ sư phần cứng nhúng và RTOS, chuyên về ESP32, STM32, ARM và các hệ điều hành thời gian thực.",
    "agency-evidence-collector": "Chuyên gia QA 'ám ảnh' bằng chứng hình ảnh, săn lùng lỗi và yêu cầu minh chứng trực quan cho mọi thứ.",
    "agency-executive-summary-generator": "Chuyên gia AI cấp cố vấn chiến lược, tóm tắt các vấn đề kinh doanh phức tạp theo khung chuẩn McKinsey/BCG.",
    "agency-experiment-tracker": "Quản lý dự án chuyên về thiết kế thử nghiệm A/B và ra quyết định dựa trên dữ liệu phân tích.",
    "agency-feedback-synthesizer": "Chuyên gia thu thập và tổng hợp phản hồi người dùng đa kênh để rút ra các thông tin sản phẩm hành động.",
    "agency-finance-tracker": "Chuyên gia phân tích tài chính và kiểm soát, quản lý ngân sách và tối ưu hóa dòng tiền doanh nghiệp.",
    "agency-frontend-developer": "Lập trình viên frontend chuyên nghiệp, chuyên về React/Vue/Angular và tối ưu hóa trải nghiệm UI/UX.",
    "agency-game-audio-engineer": "Chuyên gia âm thanh tương tác trong game, thành thạo FMOD/Wwise và âm thanh không gian.",
    "agency-game-designer": "Kiến trúc sư hệ thống game, chuyên về GDD, tâm lý người chơi và vòng lặp gameplay.",
    "agency-git-workflow-master": "Chuyên gia quy trình Git, chiến lược phân nhánh và các quy chuẩn kiểm soát phiên bản hiện đại.",
    "agency-government-digital-presales-consultant": "Cố vấn tiền bán hàng cho thị trường chính phủ, thành thạo chính sách, hồ sơ thầu và tuân thủ kỹ thuật.",
    "agency-growth-hacker": "Chiến lược gia tăng trưởng, chuyên thu hút người dùng nhanh qua thử nghiệm dữ liệu và vòng lặp viral.",
    "agency-healthcare-marketing-compliance-specialist": "Chuyên gia tuân thủ marketing y tế, thành thạo luật quảng cáo dược phẩm và bảo vệ quyền riêng tư bệnh nhân.",
    "agency-identity-graph-operator": "Người vận hành biểu đồ danh tính chung cho các AI agent trong hệ thống đa tác nhân.",
    "agency-image-prompt-engineer": "Chuyên gia prompt hình ảnh, biến khái niệm thị giác thành ngôn ngữ chính xác cho AI tạo ảnh nghệ thuật.",
    "agency-incident-response-commander": "Chỉ huy ứng phó sự cố hệ thống, điều phối phản ứng có cấu trúc và tổ chức post-mortem.",
    "agency-inclusive-visuals-specialist": "Chuyên gia hình ảnh bao trùm, loại bỏ định kiến AI để tạo nội dung chính xác về văn hóa.",
    "agency-infrastructure-maintainer": "Chuyên gia duy trì hạ tầng hệ thống, tập trung vào độ tin cậy, bảo mật và tối ưu chi phí.",
    "agency-instagram-curator": "Chuyên gia marketing Instagram, kể chuyện bằng hình ảnh và xây dựng cộng đồng gắn kết.",
    "agency-jira-workflow-steward": "Người quản lý quy trình Jira, đảm bảo commit có thể truy vết và chiến lược release an toàn.",
    "agency-legal-compliance-checker": "Chuyên gia pháp lý và tuân thủ, đảm bảo hoạt động kinh doanh tuân thủ luật pháp đa quốc gia.",
    "agency-level-designer": "Chuyên gia thiết kế màn chơi, thành thạo kể chuyện qua môi trường và nhịp độ game.",
    "agency-linkedin-content-creator": "Chuyên gia nội dung LinkedIn, xây dựng thương hiệu cá nhân và vị thế chuyên gia.",
    "agency-livestream-commerce-coach": "Huấn luyện viên bán hàng livestream, đào tạo host và vận hành phòng live chuyên nghiệp.",
    "agency-lsp-index-engineer": "Kỹ sư giao thức LSP, xây dựng hệ thống trí tuệ mã nguồn qua indexing ngữ nghĩa.",
    "agency-macos-spatial-metal-engineer": "Kỹ sư Swift và Metal, xây dựng hệ thống dựng hình 3D cho macOS và Vision Pro.",
    "agency-mcp-builder": "Chuyên gia phát triển server MCP để mở rộng khả năng của AI agent với các công cụ tùy chỉnh.",
    "agency-mobile-app-builder": "Lập trình viên ứng dụng di động chuyên nghiệp (iOS/Android) và đa nền tảng.",
    "agency-model-qa-specialist": "Chuyên gia QA mô hình ML độc lập, audit toàn diện từ tài liệu đến hiệu suất thực tế.",
    "agency-narrative-designer": "Kiến trúc sư nội dung và hội thoại game, xây dựng thế giới và câu chuyện nhập vai.",
    "agency-outbound-strategist": "Chuyên gia tiếp cận khách hàng dựa trên tín hiệu và cá nhân hóa chuyên sâu.",
    "agency-paid-media-auditor": "Kiểm toán truyền thông trả phí, đánh giá hệ thống quảng cáo qua hơn 200 tiêu chuẩn kiểm tra.",
    "agency-paid-social-strategist": "Chiến lược gia quảng cáo mạng xã hội đa nền tảng, thiết kế chiến dịch phễu đầy đủ.",
    "agency-performance-benchmarker": "Chuyên gia đo lường và tối ưu hóa hiệu năng hệ thống trên toàn bộ hạ tầng.",
    "agency-pipeline-analyst": "Chuyên gia phân tích phễu doanh thu, chẩn đoán sức khỏe pipeline và độ chính xác dự báo.",
    "agency-podcast-strategist": "Chuyên gia chiến lược podcast, định vị chương trình và phát triển khán giả audio.",
    "agency-ppc-campaign-strategist": "Chiến lược gia PPC cao cấp, kiến trúc chiến dịch tìm kiếm quy mô lớn trên Google/Amazon.",
    "agency-programmatic-display-buyer": "Chuyên gia mua quảng cáo hiển thị lập trình và chiến lược hiển thị ABM.",
    "agency-project-shepherd": "Quản lý dự án chuyên nghiệp, điều phối liên phòng ban và dẫn dắt dự án về đích.",
    "agency-proposal-strategist": "Kiến trúc sư đề xuất chiến lược, biến các cơ hội thầu thành câu chuyện thắng lợi.",
    "agency-rapid-prototyper": "Chuyên gia tạo mẫu nhanh, xây dựng POC và MVP tốc độ cao bằng công cụ hiện đại.",
    "agency-reality-checker": "Kiểm chứng thực tế, ngăn chặn các phê duyệt mơ hồ và yêu cầu bằng chứng sẵn sàng sản xuất.",
    "agency-recruitment-specialist": "Chuyên gia tuyển dụng và thu hút nhân tài, thành thạo các nền tảng và luật lao động.",
    "agency-reddit-community-builder": "Chuyên gia marketing Reddit, tương tác cộng đồng chân thực và xây dựng quan hệ lâu dài.",
    "agency-report-distribution-agent": "AI agent tự động phân phối báo cáo bán hàng cho đại diện theo khu vực quản lý.",
    "agency-sales-coach": "Huấn luyện viên bán hàng, phát triển kỹ năng nhân viên và chiến lược thương vụ.",
    "agency-sales-data-extraction-agent": "AI agent trích xuất chỉ số bán hàng từ file Excel để báo cáo trực tiếp nội bộ.",
    "agency-sales-engineer": "Kỹ sư bán hàng (tiền bán hàng), xây dựng demo và kết nối sản phẩm với mục tiêu kinh doanh.",
    "agency-search-query-analyst": "Chuyên gia phân tích truy vấn, cấu trúc từ khóa phủ định và tối ưu hóa ý định tìm kiếm.",
    "agency-security-engineer": "Kỹ sư bảo mật ứng dụng, chuyên đánh giá lỗ hổng và thiết kế kiến trúc bảo mật.",
    "agency-senior-developer": "Chuyên gia triển khai cao cấp, thành thạo Laravel, CSS nâng cao và Three.js.",
    "agency-senior-project-manager": "Quản lý dự án cao cấp, bám sát phạm vi thực tế và không bao giờ quên dự án cũ.",
    "agency-seo-specialist": "Chuyên gia chiến lược SEO, tối ưu hóa kỹ thuật và nội dung để tăng trưởng tự nhiên.",
    "agency-short-video-editing-coach": "Huấn luyện viên dựng video ngắn, thành thạo hậu kỳ và các công cụ AI hỗ trợ.",
    "agency-social-media-strategist": "Chiến lược gia mạng xã hội, xây dựng cộng đồng và quản lý tương tác thời gian thực.",
    "agency-software-architect": "Kiến trúc sư phần mềm, thiết kế hệ thống lớn và đưa ra các quyết định kỹ thuật bền vững.",
    "agency-solidity-smart-contract-engineer": "Kỹ sư Solidity, chuyên kiến trúc smart contract EVM và tối ưu hóa bảo mật.",
    "agency-sprint-prioritizer": "Chuyên gia ưu tiên Sprint, lập kế hoạch Agile và phân bổ nguồn lực dựa trên dữ liệu.",
    "agency-sre-site-reliability-engineer": "Kỹ sư tin cậy hệ thống, chuyên về SLO và giảm tải công việc vận hành thủ công.",
    "agency-studio-operations": "Quản lý vận hành studio, tối ưu hóa quy trình và điều phối nguồn lực hàng ngày.",
    "agency-studio-producer": "Lãnh đạo dự án Studio, điều phối các dự án sáng tạo và kỹ thuật ở cấp chiến lược.",
    "agency-study-abroad-advisor": "Chuyên gia tư vấn du học toàn diện cho các thị trường Âu-Mỹ-Úc và Châu Á.",
    "agency-supply-chain-strategist": "Chiến lược gia chuỗi cung ứng, xây dựng mạng lưới cung ứng hiệu quả và bền vững.",
    "agency-support-responder": "Chuyên gia phản hồi hỗ trợ, giải quyết sự cố và tối ưu hóa trải nghiệm khách hàng.",
    "agency-technical-artist": "Chuyên gia kỹ thuật mỹ thuật, thành thạo shader và tối ưu hóa tài nguyên engine.",
    "agency-technical-writer": "Chuyên gia viết tài liệu kỹ thuật, chuyển đổi khái niệm phức tạp thành hướng dẫn dễ hiểu.",
    "agency-terminal-integration-specialist": "Chuyên gia tích hợp terminal và tối ưu hóa hiển thị văn bản cho ứng dụng Swift.",
    "agency-test-results-analyzer": "Chuyên gia phân tích kết quả kiểm thử, đánh giá chất lượng từ các hoạt động testing.",
    "agency-threat-detection-engineer": "Kỹ sư phát hiện mối đe dọa, xây dựng quy tắc SIEM và đường ống detection-as-code.",
    "agency-tiktok-strategist": "Chiến lược gia TikTok, tập trung vào nội dung viral và tối ưu hóa thuật toán.",
    "agency-tool-evaluator": "Chuyên gia đánh giá công cụ công nghệ, đề xuất phần mềm tối ưu hóa năng suất.",
    "agency-tracking-measurement-specialist": "Chuyên gia đo lường chuyển đổi, quản lý tag và các mô hình phân bổ attribution.",
    "agency-trend-researcher": "Chuyên gia nghiên cứu xu hướng thị trường, phân tích đối thủ và đánh giá cơ hội.",
    "agency-twitter-engager": "Chuyên gia tương tác Twitter, xây dựng vị thế qua các thảo luận thời gian thực.",
    "agency-ui-designer": "Thiết kế UI chuyên nghiệp, xây dựng Design System và giao diện hoàn hảo từng pixel.",
    "agency-ux-architect": "Kiến trúc sư UX, cung cấp nền tảng và hướng dẫn triển khai CSS cho lập trình viên.",
    "agency-ux-researcher": "Chuyên gia nghiên cứu UX, phân tích hành vi người dùng bằng các thông tin dựa trên dữ liệu.",
    "agency-visionos-spatial-engineer": "Kỹ sư không gian VisionOS, chuyên về tính toán không gian và giao diện SwiftUI.",
    "agency-visual-storyteller": "Chuyên gia kể chuyện bằng hình ảnh, biến thông tin thành các câu chuyện thị giác lôi cuốn.",
    "agency-whimsy-injector": "Chuyên gia sáng tạo, thêm thắt cá tính và sự thú vị vào trải nghiệm thương hiệu.",
    "agency-workflow-optimizer": "Chuyên gia tối ưu hóa quy trình, tự động hóa luồng công việc để đạt năng suất cao nhất.",
    "agency-xr-cockpit-interaction-specialist": "Chuyên gia tương tác buồng lái XR, thiết kế hệ thống điều khiển trong môi trường ảo.",
    "agency-xr-immersive-developer": "Lập trình viên XR nhập vai, chuyên các ứng dụng AR/VR/XR trên trình duyệt.",
    "agency-xr-interface-architect": "Kiến trúc sư giao diện XR, thiết kế tương tác không gian cho môi trường nhập vai.",
    "api-patterns": "Nguyên tắc thiết kế API (REST, GraphQL, tRPC) và ra quyết định kiến trúc.",
    "app-builder": "Nhạc trưởng điều phối xây dựng ứng dụng toàn diện từ yêu cầu ngôn ngữ tự nhiên.",
    "architecture": "Khung ra quyết định kiến trúc, đánh giá đánh đổi và tài liệu ADR.",
    "audit-support": "Hỗ trợ tuân thủ SOX 404 với phương pháp thử nghiệm và chuẩn hóa tài liệu.",
    "awf-adaptive-language": "Điều chỉnh ngôn ngữ dựa trên trình độ kỹ thuật của người dùng.",
    "awf-auto-save": "Hệ thống tự động lưu session để không mất dữ liệu ngữ cảnh.",
    "awf-context-help": "Trợ giúp thông minh dựa trên ngữ cảnh công việc hiện tại.",
    "awf-error-translator": "Dịch lỗi kỹ thuật sang ngôn ngữ đời thường dễ hiểu.",
    "awf-onboarding": "Trải nghiệm hướng dẫn cho người dùng mới sử dụng lần đầu.",
    "awf-session-restore": "Tự động khôi phục ngữ cảnh làm việc giúp tiếp tục nhanh chóng.",
    "bash-linux": "Các mẫu terminal Bash/Linux, câu lệnh quan trọng và kỹ thuật scripting.",
    "behavioral-modes": "Các chế độ vận hành (brainstorm, implement, debug...) để thích ứng theo nhiệm vụ.",
    "brainstorming": "Quy trình đặt câu hỏi Socratic cho các yêu cầu phức tạp hoặc chưa rõ ràng.",
    "brand-voice": "Áp dụng và thực thi giọng điệu thương hiệu và hướng dẫn phong cách nội dung.",
    "call-prep": "Chuẩn bị cho cuộc gọi bán hàng với bối cảnh tài khoản và nghiên cứu người tham gia.",
    "campaign-planning": "Lập kế hoạch chiến dịch marketing, phân bổ ngân sách và xác định KPI.",
    "canned-responses": "Tạo các mẫu phản hồi cho các yêu cầu pháp lý hoặc hỗ trợ phổ biến.",
    "change-management": "Lập kế hoạch và thực hiện các thay đổi tổ chức hoặc kỹ thuật.",
    "clean-code": "Các quy chuẩn code thực dụng, ngắn gọn, không làm quá (over-engineering).",
    "close-management": "Quản lý quy trình chốt sổ tài chính cuối tháng và theo dõi trạng thái.",
    "code-review": "Review code để tìm bug, lỗ hổng bảo mật và đảm bảo khả năng bảo trì.",
    "code-review-checklist": "Các hướng dẫn review code bao quát chất lượng, bảo mật và best practices.",
    "compensation-benchmarking": "So sánh mức lương thưởng với dữ liệu thị trường để có đề xuất cạnh tranh.",
    "competitive-analysis": "Phân tích đối thủ về định vị, thông điệp và chiến lược sản phẩm.",
    "competitive-intelligence": "Nghiên cứu đối thủ và xây dựng các thẻ đối đầu (battlecard) tương tác.",
    "compliance": "Điều hướng các quy định quyền riêng tư và xử lý yêu cầu dữ liệu người dùng.",
    "compliance-tracking": "Theo dõi các yêu cầu tuân thủ và mức độ sẵn sàng cho audit chuyên sâu.",
    "content-creation": "Soạn thảo nội dung marketing đa kênh (blog, social, email) chuẩn SEO.",
    "contract-review": "Review hợp đồng dựa trên cẩm nang của tổ chức, đánh dấu các sai lệch.",
    "customer-research": "Nghiên cứu câu hỏi khách hàng dựa trên dữ liệu đa nguồn và tổng hợp câu trả lời.",
    "daily-briefing": "Bản tin bán hàng đầu ngày với các cuộc họp và ưu tiên quan trọng.",
    "data-exploration": "Khám phá bộ dữ liệu để hiểu cấu trúc và chất lượng trước khi phân tích.",
    "data-validation": "QA các báo cáo phân tích để đảm bảo tính chính xác và không có sai lệch.",
    "data-visualization": "Trực quan hóa dữ liệu hiệu quả bằng Python (matplotlib, seaborn, plotly).",
    "database-design": "Nguyên tắc thiết kế DB, schema, indexing và chiến lược ORM.",
    "deployment-procedures": "Nguyên tắc triển khai production an toàn và chiến lược rollback khi cần.",
    "design-critique": "Đánh giá thiết kế về tính khả dụng, phân cấp thị giác và tính nhất quán.",
    "design-handoff": "Tạo tài liệu bàn giao kỹ thuật chi tiết từ các bản thiết kế UI/UX.",
    "design-system-management": "Quản lý Design Tokens, thư viện component và tài liệu quy chuẩn thiết kế.",
    "documentation": "Viết và duy trì tài liệu kỹ thuật, README và hướng dẫn vận hành.",
    "documentation-templates": "Các mẫu tài liệu và hướng dẫn cấu trúc chuẩn AI-friendly.",
    "draft-outreach": "Nghiên cứu khách hàng tiềm năng và soạn thảo nội dung tiếp cận cá nhân hóa.",
    "employee-handbook": "Giải đáp các câu hỏi về chính sách công ty, phúc lợi và quy trình nội bộ.",
    "escalation": "Đóng gói các yêu cầu hỗ trợ chuyển cấp cho đội kỹ thuật hoặc lãnh đạo.",
    "feature-spec": "Viết tài liệu yêu cầu sản phẩm (PRD) với User Stories và tiêu chí thành công.",
    "financial-statements": "Tạo báo cáo kết quả kinh doanh và bảng cân đối kế toán chuẩn GAAP.",
    "frontend-design": "Tư duy thiết kế và ra quyết định cho giao diện web thẩm mỹ.",
    "game-development": "Nhạc trưởng điều phối phát triển game, điều hướng đến các skill chuyên biệt.",
    "geo-fundamentals": "Tối ưu hóa nội dung cho các công cụ tìm kiếm AI (Generative Engine Optimization).",
    "i18n-localization": "Mẫu thiết kế đa ngôn ngữ và quản lý bản dịch (L10n/I18n).",
    "incident-response": "Điều phối và quản lý các sự cố hệ thống ngay lập tức.",
    "instrument-data-to-allotrope": "Chuyển đổi dữ liệu thiết bị phòng thí nghiệm sang chuẩn ASM JSON.",
    "intelligent-routing": "Tự động chọn agent và điều phối nhiệm vụ thông minh theo yêu cầu.",
    "interactive-dashboard-builder": "Xây dựng dashboard HTML tương tác, không cần server để hoạt động.",
    "interview-prep": "Tạo kế hoạch phỏng vấn có cấu trúc với bộ câu hỏi dựa trên năng lực.",
    "journal-entry-prep": "Chuẩn bị các bút toán kế toán cho quy trình chốt sổ tháng.",
    "knowledge-management": "Xây dựng bài viết cơ sở tri thức từ các vấn đề hỗ trợ đã giải quyết.",
    "knowledge-synthesis": "Tổng hợp kết quả tìm kiếm đa nguồn thành câu trả lời thống nhất.",
    "kwp-admin-nd30": "Soạn thảo văn bản hành chính chuẩn Nghị định 30/2020/NĐ-CP.",
    "legal-risk-assessment": "Đánh giá và phân loại rủi ro pháp lý theo mức độ nghiêm trọng.",
    "lint-and-validate": "Kiểm soát chất lượng tự động, linting và phân tích tĩnh sau khi sửa code.",
    "mcp-builder": "Nguyên tắc xây dựng server MCP, thiết kế công cụ và tài nguyên.",
    "meeting-briefing": "Chuẩn bị tài liệu briefing và theo dõi các hành động sau cuộc họp.",
    "memory-management": "Hệ thống bộ nhớ hai tầng giúp AI hiểu các thuật ngữ nội bộ của bạn.",
    "metrics-tracking": "Xác định và theo dõi các chỉ số sản phẩm cùng các khung mục tiêu (OKRs).",
    "mobile-design": "Tư duy thiết kế ưu tiên di động (Mobile-first) cho iOS và Android.",
    "nda-triage": "Sàng lọc và phân loại mức độ rủi ro của các hợp đồng bảo mật (NDA).",
    "nextflow-development": "Chạy các đường ống tin sinh học nf-core trên dữ liệu giải trình tự.",
    "nodejs-best-practices": "Nguyên tắc phát triển Node.js, framework và bảo mật phía server.",
    "org-planning": "Lập kế hoạch nhân sự, thiết kế tổ chức và tối ưu cấu trúc đội ngũ.",
    "parallel-agents": "Các mẫu điều phối đa tác nhân chạy song song cho nhiệm vụ phức tạp.",
    "people-analytics": "Phân tích dữ liệu nhân sự về biến động, gắn kết và năng suất lao động.",
    "performance-analytics": "Phân tích hiệu quả marketing qua các chỉ số then chốt và xu hướng.",
    "performance-profiling": "Các phương pháp đo lường, phân tích và tối ưu hóa hiệu năng phần mềm.",
    "plan-writing": "Lập kế hoạch công việc có cấu trúc với các phụ thuộc và tiêu chí xác minh.",
    "powershell-windows": "Các mẫu PowerShell cho Windows, xử lý lỗi và các bẫy kỹ thuật thường gặp.",
    "process-optimization": "Phân tích và cải thiện các quy trình kinh doanh hiện có.",
    "python-patterns": "Nguyên tắc phát triển Python, cấu trúc dự án và các pattern hiện đại.",
    "react-best-practices": "Tối ưu hóa hiệu năng React và Next.js từ kỹ thuật của Vercel.",
    "reconciliation": "Đối soát tài khoản giữa số dư sổ cái và các báo cáo bên thứ ba.",
    "recruiting-pipeline": "Theo dõi và quản lý các giai đoạn trong phễu tuyển dụng nhân tài.",
    "red-team-tactics": "Các chiến thuật tấn công mô phỏng (Red team) dựa trên MITRE ATT&CK.",
    "resource-planning": "Lập kế hoạch và tối ưu hóa việc phân bổ nguồn lực (nhân sự, ngân sách).",
    "response-drafting": "Soạn thảo các phản hồi khách hàng chuyên nghiệp, thấu cảm và đúng ngữ cảnh.",
    "risk-assessment": "Xác định, đánh giá và giảm thiểu các rủi ro vận hành doanh nghiệp.",
    "roadmap-management": "Lập kế hoạch và ưu tiên lộ trình sản phẩm (Now/Next/Later).",
    "rust-pro": "Thành thạo Rust 1.75+ với async pattern và hệ thống type nâng cao.",
    "scientific-problem-selection": "Hỗ trợ nhà khoa học lựa chọn vấn đề nghiên cứu và chiến lược khoa học.",
    "scvi-tools": "Học sâu cho phân tích tế bào đơn bằng công cụ scvi-tools.",
    "search-strategy": "Chiến lược phân rã câu hỏi và điều phối tìm kiếm đa nguồn.",
    "seo-fundamentals": "Nguyên tắc SEO bản chất, E-E-A-T và thuật toán tìm kiếm của Google.",
    "server-management": "Nguyên tắc quản lý máy chủ, giám sát và ra quyết định mở rộng.",
    "single-cell-rna-qc": "Thực hiện kiểm soát chất lượng dữ liệu RNA-seq tế bào đơn.",
    "source-management": "Quản lý các nguồn tri thức MCP cho tìm kiếm doanh nghiệp.",
    "sql-queries": "Viết SQL hiệu năng cao trên các nền tảng (Snowflake, BigQuery, Postgres).",
    "stakeholder-comms": "Soạn thảo cập nhật cho cổ đông, lãnh đạo hoặc đối tác tùy loại đối tượng.",
    "statistical-analysis": "Áp dụng phương pháp thống kê để giải mã ý nghĩa của dữ liệu.",
    "system-design": "Thiết kế hệ thống, dịch vụ và kiến trúc phần mềm quy mô lớn.",
    "systematic-debugging": "Phương pháp gỡ lỗi hệ thống 4 bước với phân tích nguyên nhân gốc rễ.",
    "tailwind-patterns": "Sử dụng Tailwind CSS v4 với cấu trúc ưu tiên CSS và tokens.",
    "task-management": "Quản lý công việc đơn giản thông qua file chia sẻ TASKS.md.",
    "tdd-workflow": "Quy trình phát triển hướng kiểm thử (TDD) theo chu kỳ Red-Green-Refactor.",
    "tech-debt": "Xác định, phân loại và ưu tiên các nợ kỹ thuật cần giải quyết.",
    "testing-patterns": "Các mẫu kiểm thử đơn vị, tích hợp và chiến lược giả lập (mocking).",
    "testing-strategy": "Thiết kế chiến lược và kế hoạch kiểm thử tổng thể cho dự án.",
    "ticket-triage": "Phân loại và điều hướng các ticket hỗ trợ khách hàng theo mức độ ưu tiên.",
    "user-research": "Lập kế hoạch, thực hiện và tổng hợp các nghiên cứu người dùng.",
    "user-research-synthesis": "Tổng hợp nghiên cứu định tính và định lượng thành các bài học sâu sắc.",
    "ux-writing": "Viết nội dung microcopy cho giao diện người dùng (nút bấm, thông báo lỗi).",
    "variance-analysis": "Phân tích chênh lệch tài chính và giải thích các yếu tố tác động.",
    "vendor-management": "Đánh giá, so sánh và quản lý mối quan hệ với các nhà cung cấp.",
    "vulnerability-scanner": "Phân tích lỗ hổng bảo mật nâng cao theo chuẩn OWASP 2025.",
    "web-design-guidelines": "Review code UI theo các tiêu chuẩn giao diện web và khả năng truy cập.",
    "webapp-testing": "Nguyên tắc kiểm thử web ứng dụng toàn diện (E2E, Playwright).",
}

def translate():
    if not os.path.exists(JSON_FILE):
        print("File not found")
        return

    with open(JSON_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    updated_count = 0
    for skill in data:
        name = skill.get('name')
        if name in translations:
            skill['description'] = translations[name]
            updated_count += 1
        elif skill.get('description') == "":
             skill['description'] = "Chưa có mô tả kỹ năng."
             updated_count += 1

    with open(JSON_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Updated {updated_count} skills with Vietnamese descriptions.")

if __name__ == "__main__":
    translate()
